# Generated by Django 4.2.1 on 2023-06-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_i_ching_app', '0002_remove_hexagramline_monogram_symbol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hexagram',
            options={'ordering': ['hexagram_id']},
        ),
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['user', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trigram',
            options={'ordering': ['trigram_id']},
        ),
        migrations.AddField(
            model_name='reading',
            name='gpt_interpretation',
            field=models.TextField(blank=True, db_comment='Optional field resulting from the user generating an AI Interpretation for this reading', default=None, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='user_notes',
            field=models.TextField(blank=True, db_comment='Optional field that allows users to enter their own notes on this reading', default=None, null=True),
        ),
    ]
