# Generated by Django 4.2.1 on 2023-06-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_i_ching_app', '0004_userdetail_usercredithistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='fifth_line_type',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='first_line_type',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='fourth_line_type',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='second_line_type',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='sixth_line_type',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='third_line_type',
        ),
        migrations.AddField(
            model_name='hexagram',
            name='binary_value_string',
            field=models.CharField(db_comment="The values of each line represented as a string, ordered bottom to top (eg. '011001')", default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='linetype',
            name='binary_value',
            field=models.SmallIntegerField(db_comment='Represents the binary value (0=yin, 1=yang) that corresponds with this line type as it relates to consulting the oracle with coins or yarrow stalks', default=0),
        ),
        migrations.AddField(
            model_name='reading',
            name='value_string',
            field=models.CharField(db_comment="The values of each line represented as a string, ordered bottom to top (eg. '677869')", default='888888', max_length=6),
        ),
    ]
