# Generated by Django 4.2.1 on 2023-06-19 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visual_i_ching_app', '0005_remove_reading_fifth_line_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='resulting_hexagram',
            field=models.ForeignKey(blank=True, db_comment='Foreign key, references hexgrams.hexagram_id, represents the hexagram that results from the changes in this reading (if there are no changes, this value is null)', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resulting_hexagram_ids', to='visual_i_ching_app.hexagram'),
        ),
    ]
