# Generated by Django 4.2.1 on 2023-06-27 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visual_i_ching_app', '0006_alter_reading_resulting_hexagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredithistory',
            name='credits_bundle_name',
        ),
        migrations.RemoveField(
            model_name='usercredithistory',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='usercredithistory',
            name='stripe_payment_intent_id',
        ),
        migrations.AlterField(
            model_name='usercredithistory',
            name='history_type',
            field=models.CharField(db_comment="String indicating the type of credit event this record represents (eg. 'Purchase', 'Redemption', etc.)", max_length=500),
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_success', models.BooleanField(db_comment='Boolean indicating whether or not the payment was successful.', default=False)),
                ('stripe_checkout_id', models.CharField(db_comment='External identifier from Stripe representing the checkout.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Time (in UTC) at which this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Time (in UTC) at which this record was most recently updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment="Time (in UTC) at which this record was 'soft-deleted' (flagged deleted)", default=None, null=True)),
                ('user', models.ForeignKey(db_comment="Foreign key, references Django's built-in users.id, represents the user that is checking out", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_payments',
                'db_table_comment': 'A historical record for each Stripe payment, including an initial record created at the time of user creation.',
                'ordering': ['user', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='usercredithistory',
            name='user_payment',
            field=models.ForeignKey(blank=True, db_comment="Only populated for 'Purchase' records, foreign key referencing user_payments.id record indicating the Stripe Checkout event related to this credit bundle purchase", default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visual_i_ching_app.userpayment'),
        ),
    ]
