# Generated by Django 4.2.1 on 2023-06-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_i_ching_app', '0007_remove_usercredithistory_credits_bundle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_credits', models.SmallIntegerField(db_comment='Represents the number of AI Interpretation Credits included in this bundle.')),
                ('price', models.SmallIntegerField(db_comment='Represents the price in dollars of this bundle.')),
                ('price_per_credit', models.DecimalField(db_comment='Represents the price in dollars of each credit in this bundle.', decimal_places=2, max_digits=10)),
                ('stripe_price_id', models.CharField(db_comment='External identifier from Stripe representing the unique Price object for this bundle.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Time (in UTC) at which this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Time (in UTC) at which this record was most recently updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment="Time (in UTC) at which this record was 'soft-deleted' (flagged deleted)", default=None, null=True)),
            ],
            options={
                'db_table': 'credit_bundles',
                'db_table_comment': 'A record containing details for each credit bundle offered on visualiching.com.',
            },
        ),
    ]
