# Generated by Django 4.2.1 on 2023-06-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_i_ching_app', '0008_creditbundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='current_credits',
            field=models.IntegerField(db_comment="Represents this user's current number of credits available (1 credit can be exchanged for 1 AI-assisted interpretation on a reading)", default=0),
        ),
    ]
