"""
Django settings for visualiching project.

Generated by 'django-admin startproject' using Django 4.2.1.
"""

import os
import sys
import dj_database_url
from pathlib import Path
from distutils.util import strtobool
from dotenv import load_dotenv


load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent
DATABASE_URL = os.getenv('DATABASE_URL')
SECRET_KEY = os.getenv('SECRET_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
DEBUG = strtobool(os.getenv('DEBUG_FLAG'))
WORKING_ENV = os.getenv('WORKING_ENV').lower()

if WORKING_ENV == 'dev':
    ALLOWED_HOSTS = [
        'www.visualiching.com',
        'visualiching.com',
        'visualiching.herokuapp.com',
        '.localhost', 
        '127.0.0.1', 
        '[::1]'
    ]
else:
    ALLOWED_HOSTS = [
        'www.visualiching.com',
        'visualiching.com',
        'visualiching.herokuapp.com'
    ]

INSTALLED_APPS = [
    'visual_i_ching_app',
    'users_app',
    'crispy_forms',
    'crispy_bootstrap5',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_auto_logout.middleware.auto_logout',
    'visualiching.middleware.heroku_redirect_middleware.HerokuRedirectMiddleware',
]

ROOT_URLCONF = 'visualiching.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'visual_i_ching_app' / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_auto_logout.context_processors.auto_logout_client',
            ],
        },
    },
]

WSGI_APPLICATION = 'visualiching.wsgi.application'

# Use postgres DATABASE_URL if provided, otherwise use default sqlite3 database
db_from_env = dj_database_url.config(default=DATABASE_URL)

if db_from_env:
    DATABASES = {'default': db_from_env}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
    print("No valid DATABASE_URL found. Falling back to local SQLite database.")

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'
LOGIN_REDIRECT_URL = 'visual-i-ching-app-home'
LOGIN_URL = 'login'

EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = os.getenv('VISUALICHING_SENDGRID_API_KEY')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'notifications@visualiching.com'

if WORKING_ENV == 'dev':
    SECURE_SSL_REDIRECT = False
else:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True

AUTO_LOGOUT = {
    'IDLE_TIME': 3600, # logout after 1 hour of inactivity
    'MESSAGE': 'You have been automatically logged out, please login again.',
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True, # refresh page if browser window open
}

if WORKING_ENV == 'dev':
    REDIRECT_DOMAIN = 'http://localhost:8000/'
else:
    REDIRECT_DOMAIN = 'https://www.visualiching.com/'